/*
    DIrrlicht - D Bindings for Irrlicht Engine

    Copyright (C) 2014- Danyal Zia (catofdanyal@yahoo.com)

    This software is provided 'as-is', without any express or
    implied warranty. In no event will the authors be held
    liable for any damages arising from the use of this software.

    Permission is granted to anyone to use this software for any purpose,
    including commercial applications, and to alter it and redistribute
    it freely, subject to the following restrictions:

    1. The origin of this software must not be misrepresented;
       you must not claim that you wrote the original software.
       If you use this software in a product, an acknowledgment
       in the product documentation would be appreciated but
       is not required.

    2. Altered source versions must be plainly marked as such,
       and must not be misrepresented as being the original software.

    3. This notice may not be removed or altered from any
       source distribution.
*/

module dirrlicht.randomizer;

@nogc nothrow extern(C++, irr) {
	/// Interface for generating random numbers
	interface IRandomizer {
		/// resets the randomizer
		/** 
		* Params:
		* value = Initialization value (seed) 
		*/
		void reset(int value=0x0f0f0f0f);

		/// generates a pseudo random number in the range 0..randMax()
		int rand() const;

		/// generates a pseudo random number in the range 0..1
		float frand() const;

		/// get maxmimum number generated by rand()
		int randMax() const;
	}
}

unittest {
	import dirrlicht.compileconfig;
	mixin(Irr_TestBegin);

	with(device.randomizer) {
		reset();
		writeln("Rand: ", rand());
		writeln("Frand: ", frand());
		writeln("RandMax: ", randMax());
	}

	mixin(Irr_TestEnd);
}

@nogc nothrow package extern (C):

struct irr_IRandomizer;
